server:
  port: 8080
  error:
    include-message: always
  ssl:
    enabled: false
    enabled-protocols: TLSv1.2
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
  tomcat:
    accesslog:
      request-attributes-enabled: true

logging:
  level:
    root: INFO
    "[acm.internal.certification]": INFO

spring:
  docker:
    compose:
      enabled: false
  profiles:
    active: dev
  application:
    name: certification
  datasource:
    url: jdbc:sqlite:certificate.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  gmail-api:
    refresh-token: ${GMAIL_REFRESH_TOKEN:}
    user-email: ${GMAIL_USER_EMAIL:}

jwt:
  secret: nyanpasu
verify:
  base:
    frontend: https://pecacm.in/
