name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dockerfile", "main" ]


jobs:

  build_and_push:
    name: CI
    environment: dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        env:
          IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/acm-website:latest
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Push Image
        env:
          IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/acm-website:latest
        run: docker push ${{ env.IMAGE_NAME }}