name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - 'main'


jobs:

  build_and_push:
    name: CI
    environment: dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build JAR with maven
        env:
          DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DB_URL: ${{ secrets.POSTGRES_URL }}
          MAIL_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          MAIL_ID: ${{ secrets.SMTP_EMAIL }}
        run: mvn clean package spring-boot:repackage -DPOSTGRESQL_DB_URL="${{ env.DB_URL }}" -DPOSTGRESQL_DB_USER=postgres -DPOSTGRESQL_DB_PASSWORD=${{ env.DB_PASSWORD }} -DSMTP_EMAIL=${{ env.MAIL_ID }} -DSMTP_PASSWORD=${{ env.MAIL_PASSWORD }}

      - name: Build the Docker image
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/acm-website:latest
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Push Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/acm-website:latest
        run: docker push ${{ env.IMAGE_NAME }}
