name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dockerfile", "main" ]


jobs:

  build:
    name: Build docker image
    environment: dockerhub
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/acm-website:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

  push_to_registry:
    name: Push Docker image to Docker Hub
    environment: dockerhub
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/acm-website:latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Push Image
        run: docker push ${{ env.IMAGE_NAME }}